markdown: kramdown
pygments: false
permalink: /chapters/:title
rdiscount:
  extensions: [smart]
kramdown:
 use_coderay: true
 coderay:
  coderay_wrap: div
  coderay_line_numbers: nil
  coderay_tab_width: 4
  coderay_bold_every: 10
  coderay_css: class
title : Let's Build a Compiler (in Haskell)
production_url : http://g-ford.github.io
exclude: ['bower_components', 'node_modules', 'script']
# description: "Througths, flamewars, utilities, tutorials, codes, projects and other things by Carlos Alexandro Becker."
# disqus_shortname: caarlos0blog
# analytics: UA-32899481-1
# gauges: 50f2b533613f5d7c8000000c
baseurl : /cradle
author :
  name : Geoff Ford
  github : g-ford
  email: g_ford@hotmail.com
